/**
 * Hive service — registration and lifecycle of beehives.
 *
 * A beekeeper's own hives are reachable through `/hives` (the API narrows the
 * list to their apiary) and through `/beekeepers/me/hives`. The hive code is
 * generated by the backend and is never sent by the client.
 *
 * Nothing in this module interprets a reading: it fetches and returns what the
 * API stored.
 */

import { ENDPOINTS } from '@/constants/api';
import { http } from '@/services/apiClient';

/** Build the query string for a hive list request, omitting empty filters. */
function listParams({
  page,
  pageSize,
  search,
  status,
  district,
  state,
  beeSpecies,
  colonyStrength,
  hasDevice,
  hasCluster,
  includeRemoved,
  beekeeperId,
}) {
  return {
    page,
    page_size: pageSize,
    ...(search ? { search } : {}),
    ...(status ? { status } : {}),
    ...(district ? { district } : {}),
    ...(state ? { state } : {}),
    ...(beeSpecies ? { bee_species: beeSpecies } : {}),
    ...(colonyStrength ? { colony_strength: colonyStrength } : {}),
    ...(hasDevice === undefined || hasDevice === null ? {} : { has_device: hasDevice }),
    // Staff-only: `false` lists the hives whose owner is in no cluster — the
    // worklist the placement action below works from. The API ignores it for a
    // beekeeper rather than answering for apiaries they do not own.
    ...(hasCluster === undefined || hasCluster === null ? {} : { has_cluster: hasCluster }),
    ...(includeRemoved ? { include_removed: true } : {}),
    ...(beekeeperId ? { beekeeper_id: beekeeperId } : {}),
  };
}

export async function listHives(options = {}) {
  const { data, meta } = await http.get(ENDPOINTS.hives.list, {
    params: listParams({ page: 1, pageSize: 20, ...options }),
  });
  return { hives: data, meta };
}

/** Every hive the signed-in beekeeper owns (convenience listing). */
export async function listMyHives(options = {}) {
  const { data, meta } = await http.get(ENDPOINTS.hives.mine, {
    params: listParams({ page: 1, pageSize: 100, ...options }),
  });
  return { hives: data, meta };
}

export async function getHive(hiveId) {
  const { data } = await http.get(ENDPOINTS.hives.detail(hiveId));
  return data;
}

/** Register a hive. Omit `hive_code`: the backend derives it from the district. */
export async function createHive(payload) {
  const { data } = await http.post(ENDPOINTS.hives.list, payload);
  return data;
}

export async function updateHive(hiveId, changes) {
  const { data } = await http.put(ENDPOINTS.hives.detail(hiveId), changes);
  return data;
}

export async function setHiveStatus(hiveId, status, reason) {
  const { data } = await http.patch(ENDPOINTS.hives.status(hiveId), {
    status,
    ...(reason ? { reason } : {}),
  });
  return data;
}

/**
 * Remove a hive.
 *
 * The API answers 409 when the hive still has devices or readings, with the
 * counts in `details` — the caller decides whether to ask again with `force`,
 * which retires the hive (status REMOVED) instead of erasing its history.
 */
export async function deleteHive(hiveId, { force = false } = {}) {
  const { data } = await http.delete(ENDPOINTS.hives.detail(hiveId), {
    params: force ? { force: true } : {},
  });
  return data;
}

export async function getHiveSummary() {
  const { data } = await http.get(ENDPOINTS.hives.summary);
  return data;
}

/**
 * Place a hive in a cluster, or clear the placement with `clusterId = null`.
 *
 * Staff only — the API refuses a beekeeper with 403, and refuses an inactive or
 * unknown cluster rather than storing a link that resolves to nothing. The
 * reason is optional and lands in the audit trail next to the change.
 */
export async function setHiveCluster(hiveId, clusterId, reason) {
  const { data } = await http.post(ENDPOINTS.hives.cluster(hiveId), {
    cluster_id: clusterId || null,
    ...(reason ? { reason } : {}),
  });
  return data;
}

/** Districts and species present in the caller's own hives. */
export async function getHiveFilterOptions() {
  const { data } = await http.get(ENDPOINTS.hives.filters);
  return data;
}
