import { useEffect, useState } from 'react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';

import { Alert } from '@/components/ui/Alert';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Modal } from '@/components/ui/Modal';
import { Select } from '@/components/ui/Select';
import { normaliseError } from '@/utils/errors';
import {
  COLONY_STRENGTH_OPTIONS,
  EMPTY_HIVE_FORM,
  hiveSchema,
  QUEEN_STATUS_OPTIONS,
} from '@/utils/validation';
import { BEE_SPECIES_OPTIONS } from '@/utils/validation';
import { useToast } from '@/hooks/useToast';
import * as hiveService from '@/services/hiveService';

/**
 * Register or edit a hive.
 *
 * The hive code is not an input: the backend derives `HIVE-<district>-00001`
 * from the location, so two beekeepers in the same district cannot collide and
 * a client cannot pick a code that already exists on a printed label.
 *
 * Every field except the notes is optional — a hive can be registered from the
 * field before its survey details are known, and filled in later.
 */

/** Form values → API payload. Blank strings become null, numbers become numbers. */
function toPayload(values) {
  const number = (value) => (value === '' || value === undefined ? null : Number(value));
  const text = (value) => (value && value.trim() !== '' ? value.trim() : null);

  return {
    bee_species: text(values.beeSpecies),
    queen_status: values.queenStatus || 'UNKNOWN',
    colony_strength: values.colonyStrength || 'UNKNOWN',
    installation_date: text(values.installationDate),
    village: text(values.village),
    mandal: text(values.mandal),
    district: text(values.district),
    state: text(values.state),
    pincode: text(values.pincode),
    latitude: number(values.latitude),
    longitude: number(values.longitude),
    notes: text(values.notes),
  };
}

/** API record → form values. */
function toFormValues(hive) {
  if (!hive) return EMPTY_HIVE_FORM;
  return {
    beeSpecies: hive.bee_species || '',
    queenStatus: hive.queen_status || 'UNKNOWN',
    colonyStrength: hive.colony_strength || 'UNKNOWN',
    installationDate: hive.installation_date || '',
    village: hive.village || '',
    mandal: hive.mandal || '',
    district: hive.district || '',
    state: hive.state || '',
    pincode: hive.pincode || '',
    latitude: hive.latitude === null || hive.latitude === undefined ? '' : String(hive.latitude),
    longitude: hive.longitude === null || hive.longitude === undefined ? '' : String(hive.longitude),
    notes: hive.notes || '',
  };
}

export function HiveFormModal({ open, hive = null, onClose, onSaved }) {
  const toast = useToast();
  const [formError, setFormError] = useState(null);
  const isEdit = Boolean(hive);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm({ resolver: zodResolver(hiveSchema), defaultValues: EMPTY_HIVE_FORM });

  useEffect(() => {
    if (!open) return;
    setFormError(null);
    reset(toFormValues(hive));
  }, [open, hive, reset]);

  const submit = async (values) => {
    setFormError(null);
    try {
      const payload = toPayload(values);
      const saved = isEdit
        ? await hiveService.updateHive(hive.id, payload)
        : await hiveService.createHive(payload);
      toast.success(
        isEdit ? `${saved.hive_code} updated` : `Hive ${saved.hive_code} registered`,
        isEdit ? undefined : 'The hive code was generated by the platform.',
      );
      onSaved?.(saved);
      onClose?.();
    } catch (caught) {
      setFormError(normaliseError(caught));
    }
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={isEdit ? `Edit ${hive.hive_code}` : 'Register a hive'}
      description={
        isEdit
          ? 'Location and colony notes only. The hive code is permanent and cannot be changed.'
          : 'The hive code is generated from the district, so it is unique and stays the same for the life of the hive.'
      }
      size="lg"
    >
      <form onSubmit={handleSubmit(submit)} className="space-y-4" noValidate>
        {formError ? (
          <Alert variant="danger" title="Could not save this hive">
            {formError.message}
          </Alert>
        ) : null}

        {isEdit ? (
          <div className="rounded-lg border border-sand-300 bg-sand-100/60 px-3 py-2 text-sm">
            <span className="text-ink-muted">Hive code</span>
            <p className="font-medium text-ink">{hive.hive_code}</p>
          </div>
        ) : null}

        <div className="grid gap-4 sm:grid-cols-2">
          <Input
            label="Bee species"
            name="beeSpecies"
            list="hive-bee-species"
            placeholder="Apis cerana indica"
            error={errors.beeSpecies?.message}
            {...register('beeSpecies')}
          />
          <datalist id="hive-bee-species">
            {BEE_SPECIES_OPTIONS.map((option) => (
              <option key={option} value={option} />
            ))}
          </datalist>

          <Select
            label="Colony strength you recorded"
            name="colonyStrength"
            options={COLONY_STRENGTH_OPTIONS}
            error={errors.colonyStrength?.message}
            hint="Your own observation — the platform does not infer this from sensor data."
            {...register('colonyStrength')}
          />
          <Select
            label="Queen status you recorded"
            name="queenStatus"
            options={QUEEN_STATUS_OPTIONS}
            error={errors.queenStatus?.message}
            {...register('queenStatus')}
          />
          <Input
            label="Installation date"
            name="installationDate"
            type="date"
            error={errors.installationDate?.message}
            {...register('installationDate')}
          />
          <Input
            label="Village"
            name="village"
            placeholder="Tenali"
            error={errors.village?.message}
            {...register('village')}
          />
          <Input
            label="Mandal"
            name="mandal"
            error={errors.mandal?.message}
            {...register('mandal')}
          />
          <Input
            label="District"
            name="district"
            hint="Used to build the hive code."
            error={errors.district?.message}
            {...register('district')}
          />
          <Input
            label="State"
            name="state"
            error={errors.state?.message}
            {...register('state')}
          />
          <Input
            label="PIN code"
            name="pincode"
            inputMode="numeric"
            maxLength={6}
            error={errors.pincode?.message}
            {...register('pincode')}
          />
          <Input
            label="Latitude"
            name="latitude"
            inputMode="decimal"
            hint="Optional, but needs a longitude alongside it."
            error={errors.latitude?.message}
            {...register('latitude')}
          />
          <Input
            label="Longitude"
            name="longitude"
            inputMode="decimal"
            error={errors.longitude?.message}
            {...register('longitude')}
          />
        </div>

        <div>
          <label htmlFor="hive-notes" className="hc-label">
            Notes
          </label>
          <textarea
            id="hive-notes"
            rows={3}
            className="hc-textarea"
            placeholder="Anything worth remembering about this hive."
            {...register('notes')}
          />
          {errors.notes?.message ? (
            <p className="mt-1 text-xs text-status-danger">{errors.notes.message}</p>
          ) : null}
        </div>

        <div className="flex justify-end gap-2 border-t border-sand-200 pt-4">
          <Button variant="secondary" onClick={onClose} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button type="submit" loading={isSubmitting}>
            {isEdit ? 'Save changes' : 'Register hive'}
          </Button>
        </div>
      </form>
    </Modal>
  );
}

export default HiveFormModal;
