import { Breadcrumb } from '@/components/common/Breadcrumb';
import { HiveRegistry } from '@/components/hives/HiveRegistry';

/**
 * `/beekeeper/hives` — the beekeeper's own apiary.
 *
 * Real screen, not a placeholder: it lists the hives the API returns for the
 * signed-in beekeeper, and registering one generates its code server-side.
 */
export default function MyHivesPage() {
  return (
    <div className="space-y-6">
      <Breadcrumb items={[{ label: 'Beekeeper', to: '/beekeeper' }, { label: 'My hives' }]} />
      <HiveRegistry
        mode="owner"
        title="My hives"
        description="Every hive registered under your beekeeper record. Codes are generated by the platform from the district and never change."
        detailBasePath="/beekeeper/hives"
        emptyTitle="No hives registered yet"
        emptyDescription="Register your first hive to start monitoring colony and IoT data."
      />
    </div>
  );
}
