"""Seed a development database with one account per role and a demo cluster.

**DEVELOPMENT ONLY.** The credentials it prints are published in the README so a
reviewer can sign in and explore every workspace. They must never be used, or
exist, in a production deployment — the script refuses to run when the
environment is production, and every row it writes is audited like any other
change.

What it creates (idempotently — re-running reports `[exists]` and changes
nothing):

| Role | Email | Notes |
| --- | --- | --- |
| `ADMIN` | `admin@honeychain.example.com` | Platform administration |
| `KVIC_OFFICER` | `kvic@honeychain.example.com` | Beekeeper review, clusters |
| `BEEKEEPER` | `beekeeper@honeychain.example.com` | Apiary record, verified, in the demo cluster |
| `CONSUMER` | `consumer@honeychain.example.com` | Self-service profile only |

It also registers one demo hive (`HIVE-GNT-00001`) for the beekeeper and one
ESP32-class device (`ESP32-GNT-0001`) attached to it, which starts OFFLINE. **No
telemetry is generated by this script** — readings only appear once the
simulator (or real hardware) sends them, and simulator readings are stored with
``source = SIMULATOR`` so they are never mistaken for real device data.

Plus one KVIC cluster (`KVIC-GNT-001`) with the beekeeper as a member, so the
directory, cluster and verification screens have something real to show.

Usage::

    python -m app.scripts.seed_dev_data
    python -m app.scripts.seed_dev_data --reset
"""

from __future__ import annotations

import argparse
import sys

from sqlalchemy import select

from app.core.config import build_settings
from app.core.database import SessionLocal
from app.core.logging import configure_logging
from app.core.security import hash_password
from app.models.enums import UserRole
from app.models.user import User
from app.repositories.beekeeper_repository import BeekeeperRepository
from app.repositories.user_repository import UserRepository
from app.schemas.beekeeper import BeekeeperCreate
from app.schemas.cluster import ClusterCreate
from app.schemas.hive import HiveCreate
from app.schemas.iot import DeviceCreate
from app.services.beekeeper_service import BeekeeperService
from app.services.cluster_service import ClusterService
from app.services.device_service import DeviceService
from app.services.hive_service import HiveService

BANNER = "=" * 78

#: (role, name, email, password, phone, state, district, organisation)
ACCOUNTS: tuple[tuple[UserRole, str, str, str, str | None, str | None, str | None, str | None], ...] = (
    (
        UserRole.ADMIN,
        "Platform Administrator",
        "admin@honeychain.example.com",
        "AdminSecure123",
        None,
        "Andhra Pradesh",
        "Guntur",
        None,
    ),
    (
        UserRole.KVIC_OFFICER,
        "KVIC Cluster Officer",
        "kvic@honeychain.example.com",
        "KvicSecure123",
        "+919876500010",
        "Andhra Pradesh",
        "Guntur",
        "KVIC Guntur Cluster",
    ),
    (
        UserRole.BEEKEEPER,
        "Ravi Kumar",
        "beekeeper@honeychain.example.com",
        "HoneyPass123",
        "+919876500011",
        "Andhra Pradesh",
        "Guntur",
        None,
    ),
    # Phase 6 fixture accounts. The processing and laboratory modules are worked by
    # two roles that hold only their own capabilities: a processor may run
    # processing and nothing in the laboratory, a laboratory technician may measure
    # and nothing about accounts or clusters. They exist here, as DEV fixtures,
    # because a workspace with no account that can open it cannot be demonstrated.
    (
        UserRole.PROCESSOR,
        "Suresh Babu (Processing Unit)",
        "processor@honeychain.example.com",
        "ProcessPass123",
        "+919876500012",
        "Andhra Pradesh",
        "Guntur",
        "Guntur Honey Processing Unit",
    ),
    (
        UserRole.LAB_TECHNICIAN,
        "Lakshmi Rao (Laboratory)",
        "labtech@honeychain.example.com",
        "LabTechPass123",
        "+919876500013",
        "Andhra Pradesh",
        "Guntur",
        "Guntur District Quality Laboratory",
    ),
    (
        UserRole.CONSUMER,
        "Anitha Reddy",
        "consumer@honeychain.example.com",
        "ConsumerPass123",
        None,
        "Andhra Pradesh",
        "Guntur",
        None,
    ),
)

BEEKEEPER_PROFILE = BeekeeperCreate(
    village="Tenali",
    mandal="Tenali",
    district="Guntur",
    state="Andhra Pradesh",
    pincode="522201",
    experience_years=7,
    bee_species="Apis cerana indica",
    number_of_hives=24,
)

#: Development-only hive. A hive record is *entered data*, not simulated
#: telemetry: every reading posted against this hive by
#: ``python -m app.scripts.hive_simulator`` is stored with
#: ``source = SIMULATOR`` and shown as such in the dashboard.
DEMO_HIVE = HiveCreate(
    bee_species="Apis cerana indica",
    village="Tenali",
    mandal="Tenali",
    district="Guntur",
    state="Andhra Pradesh",
    pincode="522201",
    latitude=16.2430,
    longitude=80.6400,
    notes="Development fixture hive. Telemetry from the simulator is labelled SIMULATOR.",
)

DEMO_DEVICE_ID = "ESP32-GNT-0001"

CLUSTER = ClusterCreate(
    cluster_name="Guntur KVIC Beekeeping Cluster",
    district="Guntur",
    state="Andhra Pradesh",
    description=(
        "Development fixture: a KVIC cluster used to demonstrate cluster management "
        "and beekeeper membership."
    ),
    coordinator_name="KVIC Cluster Officer",
    coordinator_phone="+919876500010",
)


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed development data (DEVELOPMENT ONLY).")
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Delete the seeded accounts and cluster instead of creating them.",
    )
    return parser.parse_args(argv)


def _ensure_accounts(session) -> dict[str, User]:
    """Create the fixture accounts that do not exist yet; return them by email."""
    users = UserRepository(session)
    created: dict[str, User] = {}

    for role, name, email, password, phone, state, district, organization in ACCOUNTS:
        existing = users.get_by_email(email)
        if existing is not None:
            print(f"  [exists]  {email} ({role.value})")
            created[email] = existing
            continue

        user = users.create_user(
            name=name,
            email=email,
            role=role,
            password_hash=hash_password(password),
            phone=phone,
            state=state,
            district=district,
            organization=organization,
        )
        print(f"  [created] {email} ({role.value})")
        created[email] = user

    session.commit()
    return created


def _ensure_cluster(session, *, actor: User):
    clusters = ClusterService(session)
    found, _total = clusters.list_clusters(search=CLUSTER.cluster_name, page=1, page_size=1)
    if found:
        print(f"  [exists]  cluster {found[0].cluster_code} — {found[0].cluster_name}")
        return found[0]

    # A cluster may already exist in the same district (created by an earlier
    # fixture or by hand). Reusing it keeps the development database free of
    # near-duplicate clusters.
    siblings, _total = clusters.list_clusters(
        district=CLUSTER.district, is_active=True, page=1, page_size=1
    )
    if siblings:
        print(
            f"  [reused]  cluster {siblings[0].cluster_code} — {siblings[0].cluster_name} "
            f"({CLUSTER.district})"
        )
        return siblings[0]

    cluster = clusters.create_cluster(CLUSTER, actor=actor)
    print(f"  [created] cluster {cluster.cluster_code} — {cluster.cluster_name}")
    return cluster


def _ensure_beekeeper(session, user: User):
    beekeepers = BeekeeperRepository(session)
    existing = beekeepers.get_by_user_id(user.id)
    if existing is not None:
        print(f"  [exists]  beekeeper {existing.beekeeper_code} for {user.email}")
        return existing

    beekeeper = BeekeeperService(session).create_for_user(user, BEEKEEPER_PROFILE)
    print(f"  [created] beekeeper {beekeeper.beekeeper_code} for {user.email}")
    return beekeeper


def _ensure_demo_hive(session, *, beekeeper, actor: User):
    """One hive for the seeded beekeeper so the registry is not empty (dev only)."""
    hives = HiveService(session)
    existing, _total = hives.list_hives(actor, page=1, page_size=1)
    if existing:
        print(f"  [exists]  hive {existing[0].hive_code} — {existing[0].village}")
        return existing[0]

    hive = hives.create(actor, DEMO_HIVE)
    print(f"  [created] hive {hive.hive_code} — {hive.village}, {hive.district}")
    return hive


def _ensure_demo_device(session, *, hive, actor: User):
    """One device attached to the demo hive, starting OFFLINE (it has not reported)."""
    devices = DeviceService(session)
    existing = devices.devices.get_by_device_id(DEMO_DEVICE_ID)
    if existing is not None:
        print(f"  [exists]  device {existing.device_id} on hive {existing.hive_id}")
        return existing

    device = devices.register(
        actor,
        DeviceCreate(
            device_id=DEMO_DEVICE_ID,
            device_name="Tenali field node 1",
            hive_id=hive.id,
            firmware_version="1.0.0",
        ),
    )
    print(
        f"  [created] device {device.device_id} on {hive.hive_code} "
        "(status OFFLINE until it reports)"
    )
    return device


def seed(session) -> int:
    print(BANNER)
    print("  HoneyChain development seed — DEVELOPMENT ONLY")
    print("  These credentials must never be used outside a local database.")
    print(BANNER)

    accounts = _ensure_accounts(session)
    admin = accounts["admin@honeychain.example.com"]
    officer = accounts["kvic@honeychain.example.com"]
    beekeeper_user = accounts["beekeeper@honeychain.example.com"]

    print()
    cluster = _ensure_cluster(session, actor=admin)
    beekeeper = _ensure_beekeeper(session, beekeeper_user)

    service = BeekeeperService(session)
    if beekeeper.kvic_cluster_id is None:
        service.assign_cluster(beekeeper.id, cluster.id, actor=officer)
        print(f"  [linked]  {beekeeper.beekeeper_code} → {cluster.cluster_code}")

    if beekeeper.verification_status != "VERIFIED":
        service.change_verification(
            beekeeper.id,
            status="VERIFIED",
            remarks="Development fixture: reviewed by the KVIC officer during seeding.",
            actor=officer,
        )
        print(f"  [verified] {beekeeper.beekeeper_code} → VERIFIED")

    print()
    hive = _ensure_demo_hive(session, beekeeper=beekeeper, actor=beekeeper_user)
    device = _ensure_demo_device(session, hive=hive, actor=beekeeper_user)

    print()
    print("Accounts (DEVELOPMENT ONLY):")
    for role, _name, email, password, *_rest in ACCOUNTS:
        print(f"  {role.value:13} {email:38} {password}")
    print(f"\nCluster: {cluster.cluster_code} — {cluster.cluster_name}")
    print(f"Hive:    {hive.hive_code} — {hive.village}, {hive.district} (owned by {beekeeper.beekeeper_code})")
    print(f"Device:  {device.device_id} — OFFLINE until telemetry arrives")
    print("\nNo telemetry is fabricated by this script. To see the monitoring screens")
    print("with data, run the simulator (every reading is stored as SIMULATOR):")
    print(f"  python -m app.scripts.hive_simulator --device {device.device_id} --transport http")
    print("Sign in at http://localhost:5173/login")
    print(BANNER)
    return 0


def reset(session) -> int:
    """Remove the seeded accounts and cluster (their rows cascade)."""
    print(BANNER)
    print("  HoneyChain development seed — removing fixtures")
    print(BANNER)

    users = UserRepository(session)
    for _role, _name, email, _password, *_rest in ACCOUNTS:
        user = users.get_by_email(email)
        if user is None:
            print(f"  [absent]  {email}")
            continue
        session.delete(user)
        print(f"  [deleted] {email}")

    clusters = ClusterService(session)
    found, _total = clusters.list_clusters(search=CLUSTER.cluster_name, page=1, page_size=10)
    for cluster in found:
        session.delete(cluster)
        print(f"  [deleted] cluster {cluster.cluster_code}")

    session.commit()
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    settings = build_settings()
    configure_logging(settings)

    if settings.is_production:
        print(
            "Refusing to run: the development seed must never touch a production database.",
            file=sys.stderr,
        )
        return 2

    with SessionLocal() as session:
        return reset(session) if args.reset else seed(session)


if __name__ == "__main__":  # pragma: no cover - manual entry point
    raise SystemExit(main())
