"""Beekeeper endpoints: registration side effects, self-service, directory and
the verification workflow.

The security-relevant cases matter more than the happy paths: a beekeeper must
never reach another beekeeper's record, must never be able to verify themselves,
and codes must be generated by the backend rather than supplied by a client.
"""

from __future__ import annotations

import uuid

from fastapi.testclient import TestClient

API = "/api/v1"

BEEKEEPER_BLOCK = {
    "village": "Tenali",
    "mandal": "Tenali",
    "district": "Guntur",
    "state": "Andhra Pradesh",
    "pincode": "522201",
    "experience_years": 6,
    "bee_species": "Apis cerana indica",
    "number_of_hives": 14,
}


class TestRegistrationCreatesBeekeeper:
    def test_beekeeper_row_is_created_and_pending(self, client: TestClient, register_user):
        body = register_user(
            name="Ravi Kumar",
            email="ravi.kumar@honeychain.example.com",
            role="BEEKEEPER",
            beekeeper=BEEKEEPER_BLOCK,
        )
        record = body["beekeeper"]
        assert record["verification_status"] == "PENDING"
        # Generated by the backend from the district: BKR-<DIST>-<NNNNN>.
        assert record["beekeeper_code"].startswith("BKR-")
        assert record["beekeeper_code"].endswith("00001")
        assert record["district"] == "Guntur"

    def test_codes_are_sequential_and_unique(self, client: TestClient, register_user):
        first = register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)
        second = register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)
        assert first["beekeeper"]["beekeeper_code"] != second["beekeeper"]["beekeeper_code"]
        assert second["beekeeper"]["beekeeper_code"].endswith("00002")

    def test_supplying_a_code_is_rejected(self, client: TestClient):
        """``beekeeper_code`` is backend-generated; a client cannot choose one."""
        response = client.post(
            f"{API}/auth/register",
            json={
                "name": "Code Forger",
                "email": "forger@honeychain.example.com",
                "password": "HoneyPass123",
                "role": "BEEKEEPER",
                "beekeeper": {**BEEKEEPER_BLOCK, "beekeeper_code": "BKR-GNT-99999"},
            },
        )
        assert response.status_code == 422

    def test_consumer_cannot_send_apiary_details(self, client: TestClient):
        response = client.post(
            f"{API}/auth/register",
            json={
                "name": "Curious Consumer",
                "email": "curious@honeychain.example.com",
                "password": "HoneyPass123",
                "role": "CONSUMER",
                "beekeeper": BEEKEEPER_BLOCK,
            },
        )
        assert response.status_code == 422

    def test_consumer_gets_no_beekeeper_record(self, client: TestClient, session_factory):
        from app.models.beekeeper import Beekeeper

        response = client.post(
            f"{API}/auth/register",
            json={
                "name": "Plain Consumer",
                "email": "plain.consumer@honeychain.example.com",
                "password": "HoneyPass123",
                "role": "CONSUMER",
            },
        )
        assert response.status_code == 201
        assert response.json()["data"]["beekeeper"] is None
        with session_factory() as session:
            assert session.query(Beekeeper).count() == 0

    def test_beekeeper_may_omit_the_block(self, client: TestClient, register_user):
        """A beekeeper who skips the optional details still gets a record."""
        body = register_user(role="BEEKEEPER")
        assert body["beekeeper"]["beekeeper_code"].startswith("BKR-GEN-")

    def test_home_route_is_returned_for_redirects(self, client: TestClient, register_user, consumer_payload):
        beekeeper = register_user(role="BEEKEEPER")
        assert beekeeper["home_route"] == "/beekeeper"
        assert consumer_payload["home_route"] == "/consumer"

    def test_verification_history_starts_with_the_registration_entry(
        self, client: TestClient, auth_headers, user_payload, db
    ):
        from app.models.beekeeper_verification_history import BeekeeperVerificationHistory

        rows = (
            db.query(BeekeeperVerificationHistory)
            .filter(BeekeeperVerificationHistory.beekeeper_id == uuid.UUID(user_payload["beekeeper"]["id"]))
            .all()
        )
        assert len(rows) == 1
        assert rows[0].previous_status is None
        assert str(rows[0].new_status) == "PENDING"


class TestBeekeeperSelfService:
    def test_read_own_record(self, client: TestClient, auth_headers, user_payload):
        response = client.get(f"{API}/beekeepers/me", headers=auth_headers)
        assert response.status_code == 200, response.text
        data = response.json()["data"]
        assert data["beekeeper_code"] == user_payload["beekeeper"]["beekeeper_code"]
        assert data["verification_status"] == "PENDING"
        assert data["verification_label"] == "Pending"
        # The owner block is present so the UI can show the account it belongs to.
        assert data["user"]["email"] == user_payload["user"]["email"]

    def test_update_own_record(self, client: TestClient, auth_headers):
        response = client.put(
            f"{API}/beekeepers/me",
            headers=auth_headers,
            json={"number_of_hives": 22, "bee_species": "Apis mellifera", "experience_years": 8},
        )
        assert response.status_code == 200, response.text
        data = response.json()["data"]
        assert data["number_of_hives"] == 22
        assert data["bee_species"] == "Apis mellifera"

    def test_cannot_change_code_status_or_cluster(self, client: TestClient, auth_headers, user_payload):
        """Those fields are not part of the self-service payload at all."""
        code = user_payload["beekeeper"]["beekeeper_code"]
        for payload in (
            {"beekeeper_code": "BKR-GNT-99999"},
            {"verification_status": "VERIFIED"},
            {"kvic_cluster_id": str(uuid.uuid4())},
            {"verified_at": "2026-01-01T00:00:00Z"},
        ):
            response = client.put(f"{API}/beekeepers/me", headers=auth_headers, json=payload)
            assert response.status_code == 422, payload

        unchanged = client.get(f"{API}/beekeepers/me", headers=auth_headers).json()["data"]
        assert unchanged["beekeeper_code"] == code
        assert unchanged["verification_status"] == "PENDING"

    def test_location_edit_is_mirrored_to_the_profile(self, client: TestClient, auth_headers):
        client.put(f"{API}/beekeepers/me", headers=auth_headers, json={"village": "Mangalagiri"})
        profile = client.get(f"{API}/profile", headers=auth_headers).json()["data"]
        assert profile["profile"]["village"] == "Mangalagiri"
        assert profile["beekeeper"]["village"] == "Mangalagiri"

    def test_non_beekeeper_is_forbidden(self, client: TestClient, consumer_headers):
        assert client.get(f"{API}/beekeepers/me", headers=consumer_headers).status_code == 403

    def test_requires_authentication(self, client: TestClient):
        assert client.get(f"{API}/beekeepers/me").status_code == 401


class TestBeekeeperDirectory:
    def test_admin_and_kvic_can_list(self, client: TestClient, admin_headers, kvic_headers, user_payload):
        for headers in (admin_headers, kvic_headers):
            response = client.get(f"{API}/beekeepers", headers=headers)
            assert response.status_code == 200, response.text
            data = response.json()
            assert data["meta"]["total_items"] >= 1
            codes = [row["beekeeper_code"] for row in data["data"]]
            assert user_payload["beekeeper"]["beekeeper_code"] in codes

    def test_directory_is_paginated(self, client: TestClient, admin_headers, register_user):
        for _ in range(3):
            register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)

        page_one = client.get(f"{API}/beekeepers?page=1&page_size=2", headers=admin_headers).json()
        assert len(page_one["data"]) == 2
        assert page_one["meta"]["total_items"] == 3
        assert page_one["meta"]["total_pages"] == 2

        page_two = client.get(f"{API}/beekeepers?page=2&page_size=2", headers=admin_headers).json()
        assert len(page_two["data"]) == 1

    def test_filters_by_district_status_and_search(self, client: TestClient, admin_headers, register_user):
        guntur = register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK, name="Guntur Grower")
        register_user(
            role="BEEKEEPER",
            name="Krishna Keeper",
            beekeeper={**BEEKEEPER_BLOCK, "district": "Krishna"},
        )

        by_district = client.get(f"{API}/beekeepers?district=Guntur", headers=admin_headers).json()
        assert [row["name"] for row in by_district["data"]] == ["Guntur Grower"]

        by_status = client.get(f"{API}/beekeepers?verification_status=PENDING", headers=admin_headers).json()
        assert by_status["meta"]["total_items"] == 2

        by_status_empty = client.get(
            f"{API}/beekeepers?verification_status=VERIFIED", headers=admin_headers
        ).json()
        assert by_status_empty["data"] == []
        assert by_status_empty["meta"]["total_items"] == 0

        by_search = client.get(
            f"{API}/beekeepers?search={guntur['beekeeper']['beekeeper_code']}", headers=admin_headers
        ).json()
        assert by_search["meta"]["total_items"] == 1

    def test_beekeeper_and_consumer_cannot_list(self, client: TestClient, auth_headers, consumer_headers):
        for headers in (auth_headers, consumer_headers):
            assert client.get(f"{API}/beekeepers", headers=headers).status_code == 403

    def test_a_beekeeper_cannot_read_another_record(
        self, client: TestClient, auth_headers, register_user
    ):
        other = register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)
        response = client.get(f"{API}/beekeepers/{other['beekeeper']['id']}", headers=auth_headers)
        assert response.status_code == 403

    def test_a_beekeeper_cannot_edit_another_record(self, client: TestClient, auth_headers, register_user):
        other = register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)
        response = client.put(
            f"{API}/beekeepers/{other['beekeeper']['id']}",
            headers=auth_headers,
            json={"number_of_hives": 9999},
        )
        assert response.status_code == 403

    def test_detail_includes_history_and_allowed_transitions(
        self, client: TestClient, admin_headers, user_payload
    ):
        response = client.get(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}", headers=admin_headers
        )
        assert response.status_code == 200, response.text
        data = response.json()["data"]
        assert data["beekeeper"]["beekeeper_code"] == user_payload["beekeeper"]["beekeeper_code"]
        assert len(data["verification_history"]) == 1
        assert set(data["allowed_next_statuses"]) == {"UNDER_REVIEW", "VERIFIED", "REJECTED"}

    def test_filter_options_come_from_stored_data(self, client: TestClient, admin_headers):
        empty = client.get(f"{API}/beekeepers/filters", headers=admin_headers).json()["data"]
        # Nothing stored yet, so there is nothing to offer as a filter.
        assert empty["districts"] == []

        client.post(
            f"{API}/auth/register",
            json={
                "name": "Filter Source",
                "email": "filter.source@honeychain.example.com",
                "password": "HoneyPass123",
                "role": "BEEKEEPER",
                "beekeeper": {"district": "Guntur", "state": "Andhra Pradesh"},
            },
        )
        data = client.get(f"{API}/beekeepers/filters", headers=admin_headers).json()["data"]
        assert data["districts"] == ["Guntur"]
        assert data["states"] == ["Andhra Pradesh"]
        assert "PENDING" in data["verification_statuses"]

    def test_summary_counts_are_real(self, client: TestClient, admin_headers, register_user):
        empty = client.get(f"{API}/beekeepers/summary", headers=admin_headers).json()["data"]
        assert empty["total"] == 0

        register_user(role="BEEKEEPER", beekeeper=BEEKEEPER_BLOCK)
        filled = client.get(f"{API}/beekeepers/summary", headers=admin_headers).json()["data"]
        assert filled["total"] == 1
        assert filled["by_verification_status"]["PENDING"] == 1


class TestVerificationWorkflow:
    def test_kvic_officer_verifies_a_beekeeper(
        self, client: TestClient, kvic_headers, user_payload, kvic_payload
    ):
        response = client.patch(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}/verification",
            headers=kvic_headers,
            json={"status": "VERIFIED", "remarks": "Field visit completed; apiary confirmed."},
        )
        assert response.status_code == 200, response.text
        data = response.json()["data"]
        assert data["beekeeper"]["verification_status"] == "VERIFIED"
        assert data["beekeeper"]["verified_at"] is not None
        # History is append-only: the registration entry is still there.
        assert len(data["verification_history"]) == 2
        newest = data["verification_history"][0]
        assert newest["previous_status"] == "PENDING"
        assert newest["new_status"] == "VERIFIED"
        # The decision records who made it and in what capacity, so the trail
        # stays readable even if the officer's account later changes.
        assert newest["changed_by_name"]
        assert newest["changed_by_role"] == "KVIC_OFFICER"
        assert newest["changed_by_id"] == str(kvic_payload["id"])

    def test_history_is_append_only_across_changes(
        self, client: TestClient, admin_headers, user_payload
    ):
        beekeeper_id = user_payload["beekeeper"]["id"]
        for status, remarks in (
            ("UNDER_REVIEW", "Documents received."),
            ("VERIFIED", "Details confirmed."),
            ("SUSPENDED", "Awaiting re-inspection after a complaint."),
        ):
            response = client.patch(
                f"{API}/beekeepers/{beekeeper_id}/verification",
                headers=admin_headers,
                json={"status": status, "remarks": remarks},
            )
            assert response.status_code == 200, response.text

        history = client.get(f"{API}/beekeepers/{beekeeper_id}", headers=admin_headers).json()["data"][
            "verification_history"
        ]
        assert len(history) == 4  # registration + three decisions
        assert [entry["new_status"] for entry in history] == [
            "SUSPENDED",
            "VERIFIED",
            "UNDER_REVIEW",
            "PENDING",
        ]

    def test_invalid_transition_is_rejected(self, client: TestClient, admin_headers, user_payload):
        """PENDING cannot jump straight to SUSPENDED."""
        response = client.patch(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}/verification",
            headers=admin_headers,
            json={"status": "SUSPENDED", "remarks": "Not applicable yet."},
        )
        assert response.status_code == 422
        assert "allowed_next" in response.json()["error"]["details"]

    def test_repeating_the_current_status_is_rejected(self, client: TestClient, admin_headers, user_payload):
        response = client.patch(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}/verification",
            headers=admin_headers,
            json={"status": "PENDING"},
        )
        assert response.status_code == 422

    def test_rejection_requires_a_remark(self, client: TestClient, admin_headers, user_payload):
        response = client.patch(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}/verification",
            headers=admin_headers,
            json={"status": "REJECTED"},
        )
        assert response.status_code == 422

    def test_beekeepers_and_consumers_cannot_verify(
        self, client: TestClient, auth_headers, consumer_headers, user_payload
    ):
        for headers in (auth_headers, consumer_headers):
            response = client.patch(
                f"{API}/beekeepers/{user_payload['beekeeper']['id']}/verification",
                headers=headers,
                json={"status": "VERIFIED", "remarks": "Self-approved."},
            )
            assert response.status_code == 403

        still_pending = client.get(f"{API}/beekeepers/me", headers=auth_headers).json()["data"]
        assert still_pending["verification_status"] == "PENDING"

    def test_officer_can_edit_another_beekeeper(self, client: TestClient, kvic_headers, user_payload):
        response = client.put(
            f"{API}/beekeepers/{user_payload['beekeeper']['id']}",
            headers=kvic_headers,
            json={"number_of_hives": 30},
        )
        assert response.status_code == 200
        assert response.json()["data"]["number_of_hives"] == 30

    def test_unknown_beekeeper_is_not_found(self, client: TestClient, admin_headers):
        response = client.get(f"{API}/beekeepers/{uuid.uuid4()}", headers=admin_headers)
        assert response.status_code == 404


class TestBeekeeperScopeGuards:
    """Scope guards across phases.

    Phase 3 added the hive registry, so ``/hives`` and ``/beekeepers/me/hives``
    now answer for a beekeeper; Phase 5 added collections and honey batches, so
    those answer too. Processing, laboratory, packaging, distribution and any
    traceability ledger stay unimplemented until their own phases — this test
    still fails loudly if one of them is half-built.
    """

    def test_hive_endpoints_are_available_to_a_beekeeper(self, client: TestClient, auth_headers):
        for path in (f"{API}/beekeepers/me/hives", f"{API}/hives"):
            assert client.get(path, headers=auth_headers).status_code == 200, path

    def test_phase_five_records_are_available_to_a_beekeeper(
        self, client: TestClient, auth_headers
    ):
        for path in (f"{API}/collections", f"{API}/collections/summary", f"{API}/batches"):
            assert client.get(path, headers=auth_headers).status_code == 200, path

    def test_later_phase_modules_are_still_absent(self, client: TestClient, auth_headers):
        """Nothing beyond Phase 6 may quietly appear: no packaging, no distribution,
        no customer verification, no ledger.

        Processing and laboratory shipped in Phase 6 and have their own suites; the
        point of this check is that the phases after them are still absent rather
        than half-present.
        """
        for path in (
            f"{API}/harvests",
            f"{API}/packaging/lots",
            f"{API}/distribution/shipments",
            f"{API}/supply-chain/batches",
            f"{API}/ai/insights",
            f"{API}/blockchain/anchors",
            f"{API}/customer/verify",
        ):
            assert client.get(path, headers=auth_headers).status_code == 404, path
