"""Shared model mixins: UUID identifiers and audit timestamps."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base

#: Native UUID on PostgreSQL. The SQLite variant exists solely so the test
#: suite (or a scratch script) can run without a database server; production
#: always uses PostgreSQL, where ``gen_random_uuid()`` is available natively.
UUID_TYPE = PG_UUID(as_uuid=True).with_variant(String(36), "sqlite")


class UUIDPrimaryKeyMixin:
    """Adds a client-safe UUID primary key generated by the database.

    UUIDs keep identifiers non-enumerable in QR payloads and public trace URLs
    (Phase 3) while still being index-friendly on PostgreSQL.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        doc="Primary identifier (UUID v4).",
    )


class TimestampMixin:
    """Adds timezone-aware ``created_at`` / ``updated_at`` audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        doc="Row creation timestamp (UTC).",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        doc="Last modification timestamp (UTC).",
    )


__all__ = ["Base", "UUID_TYPE", "UUIDPrimaryKeyMixin", "TimestampMixin"]
