"""``beekeepers`` — the beekeeper's operational profile.

Only users with the ``BEEKEEPER`` role receive a row here; the service layer
creates it during registration. The record carries the apiary's location (which
drives cluster assignment) and the verification state, which is the platform's
answer to "has anyone actually confirmed this person and their apiary?".
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import UUID_TYPE, TimestampMixin, UUIDPrimaryKeyMixin
from app.models.enums import VerificationStatus

if TYPE_CHECKING:  # pragma: no cover
    from app.models.beekeeper_verification_history import BeekeeperVerificationHistory
    from app.models.kvic_cluster import KvicCluster
    from app.models.user import User


class Beekeeper(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A registered beekeeper and their apiary details."""

    __tablename__ = "beekeepers"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    #: Generated by the backend (never supplied by the client), e.g.
    #: ``BKR-GNT-00001``. Appears on certificates and printed records, so it is
    #: stable and never reused.
    beekeeper_code: Mapped[str] = mapped_column(String(40), nullable=False, unique=True, index=True)

    # -- Apiary practice -----------------------------------------------------
    experience_years: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bee_species: Mapped[str | None] = mapped_column(String(80), nullable=True)
    number_of_hives: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # -- Location (denormalised from the profile for filtering and reporting) -
    village: Mapped[str | None] = mapped_column(String(120), nullable=True)
    mandal: Mapped[str | None] = mapped_column(String(120), nullable=True)
    district: Mapped[str | None] = mapped_column(String(80), nullable=True, index=True)
    state: Mapped[str | None] = mapped_column(String(80), nullable=True, index=True)
    pincode: Mapped[str | None] = mapped_column(String(10), nullable=True)

    # -- Organisation --------------------------------------------------------
    kvic_cluster_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("kvic_clusters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    registration_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # -- Verification --------------------------------------------------------
    verification_status: Mapped[VerificationStatus] = mapped_column(
        SAEnum(
            VerificationStatus,
            name="verification_status",
            values_callable=lambda enum_cls: [item.value for item in enum_cls],
            native_enum=True,
            validate_strings=True,
        ),
        nullable=False,
        default=VerificationStatus.PENDING,
        server_default=VerificationStatus.PENDING.value,
        index=True,
    )
    verification_remarks: Mapped[str | None] = mapped_column(Text, nullable=True)
    verified_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "experience_years IS NULL OR (experience_years >= 0 AND experience_years <= 90)",
            name="experience_years_range",
        ),
        CheckConstraint(
            "number_of_hives IS NULL OR (number_of_hives >= 0 AND number_of_hives <= 100000)",
            name="number_of_hives_range",
        ),
        CheckConstraint(
            "pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$'",
            name="beekeeper_pincode_format",
        ),
        Index("ix_beekeepers_district_status", "district", "verification_status"),
        Index("ix_beekeepers_cluster_status", "kvic_cluster_id", "verification_status"),
    )

    # -- Relationships -------------------------------------------------------
    user: Mapped["User"] = relationship(back_populates="beekeeper", foreign_keys=[user_id])
    cluster: Mapped["KvicCluster | None"] = relationship(back_populates="beekeepers")
    verified_by: Mapped["User | None"] = relationship(foreign_keys=[verified_by_id])
    verification_history: Mapped[list["BeekeeperVerificationHistory"]] = relationship(
        back_populates="beekeeper",
        cascade="all, delete-orphan",
        order_by="BeekeeperVerificationHistory.changed_at.desc()",
    )
    # Phase 3: a beekeeper owns hives, and each device inherits that ownership.
    hives: Mapped[list["Hive"]] = relationship(  # noqa: F821
        back_populates="beekeeper",
        cascade="all, delete-orphan",
        order_by="Hive.hive_code",
    )
    devices: Mapped[list["IotDevice"]] = relationship(  # noqa: F821
        back_populates="beekeeper",
        cascade="all, delete-orphan",
        order_by="IotDevice.device_id",
    )

    # -- Helpers -------------------------------------------------------------
    @property
    def is_verified(self) -> bool:
        return self.verification_status == VerificationStatus.VERIFIED

    @property
    def location_label(self) -> str:
        """Compact location string for tables and cards."""
        parts = [part for part in (self.village, self.mandal, self.district, self.state) if part]
        return ", ".join(parts) if parts else "—"

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Beekeeper {self.beekeeper_code} status={self.verification_status}>"
