"""``hives`` — the physical hive registry.

A hive belongs to exactly one beekeeper and optionally to a KVIC cluster, and is
the anchor for everything the IoT phase collects: devices are attached to hives,
and every sensor reading is stored against the hive it came from.

Hives are never hard-deleted. A hive that is no longer in service moves to the
``REMOVED`` status so its historical readings, devices and audit trail stay
intact and interpretable.
"""

from __future__ import annotations

import uuid
from datetime import date

from sqlalchemy import (
    Enum as SAEnum,
    CheckConstraint,
    Date,
    Float,
    ForeignKey,
    Index,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin, UUID_TYPE
from app.models.enums import ColonyStrength, HiveStatus, QueenStatus

#: Reused by the migration so the database type is created and dropped once.
QUEEN_STATUS_ENUM = SAEnum(
    QueenStatus,
    name="queen_status",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)
COLONY_STRENGTH_ENUM = SAEnum(
    ColonyStrength,
    name="colony_strength",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)
HIVE_STATUS_ENUM = SAEnum(
    HiveStatus,
    name="hive_status",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)

#: Six decimal places is ~0.11 m of precision — far more than any apiary needs,
#: and it keeps stored coordinates honest rather than falsely precise.
COORDINATE_DECIMALS = 6


class Hive(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A single hive registered by a beekeeper."""

    __tablename__ = "hives"

    # -- Identity ------------------------------------------------------------
    hive_code: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        unique=True,
        index=True,
        doc="Human-readable code generated by the backend, e.g. HIVE-GNT-00001.",
    )
    beekeeper_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("beekeepers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    cluster_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("kvic_clusters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # -- Colony --------------------------------------------------------------
    bee_species: Mapped[str | None] = mapped_column(String(80), nullable=True)
    queen_status: Mapped[QueenStatus] = mapped_column(
        QUEEN_STATUS_ENUM,
        nullable=False,
        default=QueenStatus.UNKNOWN,
        server_default=QueenStatus.UNKNOWN.value,
        doc="Manually observed queen state — never inferred in this phase.",
    )
    colony_strength: Mapped[ColonyStrength] = mapped_column(
        COLONY_STRENGTH_ENUM,
        nullable=False,
        default=ColonyStrength.UNKNOWN,
        server_default=ColonyStrength.UNKNOWN.value,
        doc="Beekeeper's own assessment of colony strength.",
    )
    installation_date: Mapped[date | None] = mapped_column(Date, nullable=True)

    # -- Location ------------------------------------------------------------
    village: Mapped[str | None] = mapped_column(String(120), nullable=True)
    mandal: Mapped[str | None] = mapped_column(String(120), nullable=True)
    district: Mapped[str | None] = mapped_column(String(80), nullable=True, index=True)
    state: Mapped[str | None] = mapped_column(String(80), nullable=True)
    pincode: Mapped[str | None] = mapped_column(String(10), nullable=True)
    latitude: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        doc="GPS latitude in decimal degrees. Optional: a hive may be registered "
        "without coordinates rather than with guessed ones.",
    )
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)

    # -- Lifecycle -----------------------------------------------------------
    status: Mapped[HiveStatus] = mapped_column(
        HIVE_STATUS_ENUM,
        nullable=False,
        default=HiveStatus.ACTIVE,
        server_default=HiveStatus.ACTIVE.value,
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name="hive_latitude_range",
        ),
        CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name="hive_longitude_range",
        ),
        CheckConstraint(
            "pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$'",
            name="hive_pincode_format",
        ),
        CheckConstraint(
            "bee_species IS NULL OR length(bee_species) >= 2",
            name="hive_bee_species_min_length",
        ),
        # A hive is normally listed by owner and filtered by status; both columns
        # are used together by every directory query.
        Index("ix_hives_beekeeper_status", "beekeeper_id", "status"),
        Index("ix_hives_cluster_status", "cluster_id", "status"),
    )

    # -- Relationships -------------------------------------------------------
    beekeeper: Mapped["Beekeeper"] = relationship(back_populates="hives")  # noqa: F821
    cluster: Mapped["KvicCluster | None"] = relationship()  # noqa: F821
    devices: Mapped[list["IotDevice"]] = relationship(  # noqa: F821
        back_populates="hive", cascade="all, delete-orphan"
    )
    readings: Mapped[list["SensorReading"]] = relationship(  # noqa: F821
        back_populates="hive", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Hive {self.hive_code} status={self.status}>"


__all__ = ["Hive", "HIVE_STATUS_ENUM", "QUEEN_STATUS_ENUM", "COLONY_STRENGTH_ENUM"]
