"""``honey_collections`` and ``honey_collection_hives`` — a real harvest event.

What a collection is
--------------------
A collection *is* the harvest: the beekeeper selected hives, took honey out of
them, and recorded how much was actually taken. It is not a projection and not a
sensor reading. Three quantities in this platform are deliberately kept apart and
must never be conflated:

* ``hive_ai_analyses.predicted_yield_kg`` — what the AI *estimated* (Phase 4);
* ``sensor_readings.weight`` — what a scale *measured*, including the box, the
  frames and the bees;
* ``honey_collections.total_quantity`` — what the beekeeper actually **harvested**.

Nothing derives one from another. A collection therefore stores the harvested
figure the beekeeper entered, and snapshots the AI estimate *next to it* (never
instead of it) so the two can be compared later without either being overwritten.

Why the source hives are their own table
----------------------------------------
A harvest can draw on several hives, and the traceability requirement is that
*each* contribution stays queryable: "22.5 kg from 3 hives" is not a record, it
is a summary. ``honey_collection_hives`` keeps one row per contributing hive with
the quantity measured there, so a later batch, laboratory test or consumer query
can walk back to the individual hive.

The join rows also carry the per-hive AI estimate captured at the time of the
harvest — again as context, snapshotted rather than re-read, because an analysis
recomputed next month must not silently change what a two-year-old batch says.

Immutability
------------
Once ``status`` is ``COMPLETED`` the event is historical: the hives, the
quantities, the date, the owner and the cluster stop being writable (enforced in
the service, which is the only writer). An open collection — ``PLANNED`` or
``IN_PROGRESS`` — may still be corrected, which is how a mistake is fixed *before*
it becomes a batch. Nothing overwrites a completed record silently.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Enum as SAEnum,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin, UUID_TYPE
from app.models.enums import CollectionStatus, CollectionUnit

#: Reused by the migration so each database type is created and dropped once.
COLLECTION_STATUS_ENUM = SAEnum(
    CollectionStatus,
    name="collection_status",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)
COLLECTION_UNIT_ENUM = SAEnum(
    CollectionUnit,
    name="collection_unit",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)

#: ``Numeric(10, 3)``: a harvest is weighed to the gram, and 10 digits leaves
#: room for a nine-tonne consignment without ever needing a float. Money-free
#: quantities stay ``Decimal`` from the database to the JSON payload.
QUANTITY_PRECISION = 10
QUANTITY_SCALE = 3


class HoneyCollection(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """One honey harvesting event, by one beekeeper, from one or more hives."""

    __tablename__ = "honey_collections"

    # -- Identity ------------------------------------------------------------
    collection_code: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        unique=True,
        index=True,
        doc="Human-readable code generated by the backend, e.g. HC-COL-2026-000001.",
    )
    #: Optional client-supplied key so a retried create cannot produce a second
    #: collection. Unique per beekeeper (below), not globally: two apiaries may
    #: independently use the same form id.
    client_reference: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # -- Organisational context (derived server-side, never from a payload) ---
    beekeeper_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("beekeepers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    #: The owner's cluster at the time of the harvest. ``NULL`` when the
    #: beekeeper belongs to no cluster yet — recorded as the truth rather than
    #: guessed, and staff can resolve it later through the Phase-4.1 placement.
    cluster_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("kvic_clusters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # -- The harvest ---------------------------------------------------------
    collection_date: Mapped[date] = mapped_column(
        Date, nullable=False, index=True, doc="The day the honey was taken."
    )
    total_quantity: Mapped[Decimal] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE),
        nullable=False,
        doc="Actual harvested quantity — the sum of the per-hive contributions.",
    )
    unit: Mapped[CollectionUnit] = mapped_column(
        COLLECTION_UNIT_ENUM,
        nullable=False,
        default=CollectionUnit.KG,
        server_default=CollectionUnit.KG.value,
        doc="Mass unit the harvest was weighed in. Stored, never converted.",
    )
    status: Mapped[CollectionStatus] = mapped_column(
        COLLECTION_STATUS_ENUM,
        nullable=False,
        default=CollectionStatus.PLANNED,
        server_default=CollectionStatus.PLANNED.value,
        index=True,
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # -- AI context, snapshotted at the moment of the harvest ----------------
    ai_predicted_yield_kg: Mapped[Decimal | None] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE),
        nullable=True,
        doc=(
            "Sum of the stored per-hive AI estimates available when the harvest was "
            "recorded. An estimate, kept for context — never the harvested quantity."
        ),
    )
    ai_prediction_hive_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
        doc="How many source hives had an AI estimate. 0 means no AI context exists.",
    )
    ai_prediction_captured_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # -- Lifecycle markers ---------------------------------------------------
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    cancellation_reason: Mapped[str | None] = mapped_column(String(200), nullable=True)

    __table_args__ = (
        CheckConstraint("total_quantity > 0", name="collection_total_quantity_positive"),
        CheckConstraint(
            "ai_predicted_yield_kg IS NULL OR ai_predicted_yield_kg >= 0",
            name="collection_predicted_yield_non_negative",
        ),
        CheckConstraint(
            "ai_prediction_hive_count >= 0",
            name="collection_prediction_hive_count_non_negative",
        ),
        # A client reference identifies one harvest per beekeeper.
        UniqueConstraint("beekeeper_id", "client_reference", name="collection_client_reference_per_beekeeper"),
        # The directory queries a beekeeper's own harvests, and staff filter the
        # same rows by cluster; both order by date.
        Index("ix_collections_beekeeper_date", "beekeeper_id", "collection_date"),
        Index("ix_collections_cluster_date", "cluster_id", "collection_date"),
        Index("ix_collections_status_date", "status", "collection_date"),
    )

    # -- Relationships -------------------------------------------------------
    beekeeper: Mapped["Beekeeper"] = relationship()  # noqa: F821
    cluster: Mapped["KvicCluster | None"] = relationship()  # noqa: F821
    sources: Mapped[list["HoneyCollectionHive"]] = relationship(
        back_populates="collection",
        cascade="all, delete-orphan",
        order_by="HoneyCollectionHive.created_at",
    )
    batch: Mapped["HoneyBatch | None"] = relationship(  # noqa: F821
        back_populates="collection", uselist=False
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<HoneyCollection {self.collection_code} {self.status} {self.total_quantity}{self.unit.label}>"


class HoneyCollectionHive(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """One hive's contribution to one collection.

    A row per contributing hive — never a count in a text field — so the source
    of a batch stays queryable back to the individual hive, its owner and its
    cluster (the Phase-4.1 relationship, used unchanged).
    """

    __tablename__ = "honey_collection_hives"

    collection_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("honey_collections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    #: ``RESTRICT``: a hive that contributed honey to a recorded harvest cannot
    #: be hard-deleted out from under it. Retiring the hive (status ``REMOVED``)
    #: remains available — the registry offers it — so history is never broken by
    #: a delete.
    hive_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("hives.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    #: The hive's code at harvest time. Denormalised on purpose: a code is
    #: generated once and never changes, and having it here keeps an old harvest
    #: readable even if the hive row is later retired.
    hive_code: Mapped[str] = mapped_column(String(40), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE),
        nullable=False,
        doc="Quantity taken from this hive, in the collection's unit.",
    )
    #: The AI estimate for *this* hive when the harvest was recorded (nullable:
    #: most hives have no analysis, and none is invented).
    ai_predicted_yield_kg: Mapped[Decimal | None] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE), nullable=True
    )
    ai_analysis_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("hive_ai_analyses.id", ondelete="SET NULL"),
        nullable=True,
        doc="The stored analysis the estimate came from, so it stays verifiable.",
    )
    notes: Mapped[str | None] = mapped_column(String(200), nullable=True)

    __table_args__ = (
        CheckConstraint("quantity > 0", name="collection_hive_quantity_positive"),
        CheckConstraint(
            "ai_predicted_yield_kg IS NULL OR ai_predicted_yield_kg >= 0",
            name="collection_hive_predicted_yield_non_negative",
        ),
        # One row per hive per collection: the same hive cannot contribute twice,
        # which is what makes the total a trustworthy sum.
        UniqueConstraint("collection_id", "hive_id", name="collection_hive_unique_per_collection"),
        # "Every harvest this hive has given" — the query behind a hive's harvest
        # history — reads by hive and orders by when it was recorded.
        Index("ix_collection_hives_hive_created", "hive_id", "created_at"),
    )

    collection: Mapped["HoneyCollection"] = relationship(back_populates="sources")
    hive: Mapped["Hive"] = relationship()  # noqa: F821

    def __repr__(self) -> str:  # pragma: no cover
        return f"<HoneyCollectionHive {self.hive_code} {self.quantity}>"


__all__ = [
    "HoneyCollection",
    "HoneyCollectionHive",
    "COLLECTION_STATUS_ENUM",
    "COLLECTION_UNIT_ENUM",
    "QUANTITY_PRECISION",
    "QUANTITY_SCALE",
]
