"""``honey_batches`` — the traceable unit a completed collection produces.

One batch per completed collection
----------------------------------
The unique constraint on ``collection_id`` is the guarantee, not a convention:
retrying a completion cannot produce a second batch, and a batch can never exist
without the collection that created it. The relationship is 1:1 and enforced by
the database.

A snapshot, not a second source of truth
----------------------------------------
The batch repeats the collection's date, quantity, unit, owner and cluster. That
is deliberate: a batch is the record the supply chain will move (processing,
laboratory, packaging, distribution) and it has to stay interpretable on its own,
exactly as it was at the moment of collection, even if a later phase corrects
something upstream. What it does **not** do is originate data — every value here
was copied from the collection at creation time and none of it is writable
afterwards.

Source hives are reached through the collection (``batch → collection →
honey_collection_hives → hives``) rather than by copying the list a second time.
A duplicate list is a list that can drift; the join table is already the
authoritative record of which hives contributed and how much each gave.

Immutability
------------
``batch_code``, ``collection_id``, ``beekeeper_id``, ``cluster_id``,
``collection_date``, ``quantity``, ``unit`` and the AI snapshot are protected:
no Prompt 5 endpoint can change them, and the service refuses even if one is
added by mistake (see ``BatchService``). This is the property the later
blockchain phase depends on — a tamper-evident record is only meaningful if the
record itself does not change underneath it.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Enum as SAEnum,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin, UUID_TYPE
from app.models.enums import BatchStage, BatchStatus, CollectionUnit
from app.models.honey_collection import (
    COLLECTION_UNIT_ENUM,
    QUANTITY_PRECISION,
    QUANTITY_SCALE,
)

BATCH_STATUS_ENUM = SAEnum(
    BatchStatus,
    name="batch_status",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)
BATCH_STAGE_ENUM = SAEnum(
    BatchStage,
    name="batch_stage",
    values_callable=lambda enum_cls: [item.value for item in enum_cls],
    native_enum=True,
    validate_strings=True,
)


class HoneyBatch(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A batch of honey, produced by exactly one completed collection."""

    __tablename__ = "honey_batches"

    # -- Identity ------------------------------------------------------------
    batch_code: Mapped[str] = mapped_column(
        String(40),
        nullable=False,
        unique=True,
        index=True,
        doc="Human-readable code generated by the backend, e.g. HC-BATCH-2026-000001.",
    )
    #: One batch per collection — enforced here so a retried completion cannot
    #: create a duplicate, whatever the client does.
    collection_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("honey_collections.id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
        index=True,
    )

    # -- Organisational context, copied from the collection ------------------
    beekeeper_id: Mapped[uuid.UUID] = mapped_column(
        UUID_TYPE,
        ForeignKey("beekeepers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    cluster_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID_TYPE,
        ForeignKey("kvic_clusters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="The cluster the producing beekeeper belonged to at harvest time.",
    )

    # -- Harvest facts, snapshotted from the collection ----------------------
    collection_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    quantity: Mapped[Decimal] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE),
        nullable=False,
        doc="Actual harvested quantity, copied from the collection at creation.",
    )
    unit: Mapped[CollectionUnit] = mapped_column(COLLECTION_UNIT_ENUM, nullable=False)

    # -- Lifecycle -----------------------------------------------------------
    status: Mapped[BatchStatus] = mapped_column(
        BATCH_STATUS_ENUM,
        nullable=False,
        default=BatchStatus.COLLECTED,
        server_default=BatchStatus.COLLECTED.value,
        index=True,
        doc=(
            "COLLECTED → PROCESSING → LAB_TESTING → APPROVED/REJECTED are the states "
            "Phases 5 and 6 between them can produce, and every move is validated "
            "against BATCH_STATUS_TRANSITIONS. PACKAGED, DISTRIBUTION and COMPLETED "
            "remain reserved for the modules that will do that work."
        ),
    )
    current_stage: Mapped[BatchStage] = mapped_column(
        BATCH_STAGE_ENUM,
        nullable=False,
        default=BatchStage.COLLECTION,
        server_default=BatchStage.COLLECTION.value,
        doc="Where the batch stands on the traceability timeline.",
    )
    #: How many source hives fed this batch. A count for list screens; the
    #: relationships themselves live in ``honey_collection_hives``.
    source_hive_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )

    # -- AI context, snapshotted from the collection -------------------------
    ai_predicted_yield_kg: Mapped[Decimal | None] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE),
        nullable=True,
        doc="The AI estimate that existed at harvest time. NULL when there was none.",
    )
    ai_prediction_hive_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    #: ``quantity - ai_predicted_yield_kg``. Context for a single harvest — *not*
    #: a measure of model accuracy, which one collection cannot establish.
    prediction_difference_kg: Mapped[Decimal | None] = mapped_column(
        Numeric(QUANTITY_PRECISION, QUANTITY_SCALE), nullable=True
    )

    __table_args__ = (
        CheckConstraint("quantity > 0", name="batch_quantity_positive"),
        CheckConstraint("source_hive_count >= 0", name="batch_source_hive_count_non_negative"),
        CheckConstraint(
            "ai_predicted_yield_kg IS NULL OR ai_predicted_yield_kg >= 0",
            name="batch_predicted_yield_non_negative",
        ),
        # Staff list a cluster's batches and a beekeeper lists their own; both
        # order by the harvest date.
        Index("ix_batches_beekeeper_date", "beekeeper_id", "collection_date"),
        Index("ix_batches_cluster_date", "cluster_id", "collection_date"),
        Index("ix_batches_status_date", "status", "collection_date"),
    )

    collection: Mapped["HoneyCollection"] = relationship(back_populates="batch")  # noqa: F821
    beekeeper: Mapped["Beekeeper"] = relationship()  # noqa: F821
    cluster: Mapped["KvicCluster | None"] = relationship()  # noqa: F821
    #: What was done to the honey (Phase 6). A list, not a single row: a cancelled
    #: run stays in the history rather than being deleted.
    processing_records: Mapped[list["HoneyProcessing"]] = relationship(  # noqa: F821
        back_populates="batch"
    )
    #: Laboratory tests. More than one may exist — a retest is a new test, never
    #: an edit of the previous one, so historical results stay readable.
    lab_tests: Mapped[list["LabTest"]] = relationship(back_populates="batch")  # noqa: F821
    #: Added by Phase 7. Read-only here: the packaging and distribution modules
    #: own these rows, and the batch's own facts are never derived from them.
    packaging_records: Mapped[list["PackagingRun"]] = relationship(  # noqa: F821
        viewonly=True
    )
    packages: Mapped[list["HoneyPackage"]] = relationship(viewonly=True)  # noqa: F821
    distributions: Mapped[list["Distribution"]] = relationship(viewonly=True)  # noqa: F821

    # -- Convenience, derived from the rows above (never stored twice) --------
    @property
    def current_processing(self) -> "HoneyProcessing | None":  # noqa: F821
        """The run that is under way or the most recent one that finished."""
        rows = list(self.processing_records or [])
        open_rows = [row for row in rows if row.status.is_open]
        if open_rows:
            return max(open_rows, key=lambda row: row.created_at)
        return max(rows, key=lambda row: row.created_at) if rows else None

    @property
    def latest_lab_test(self) -> "LabTest | None":  # noqa: F821
        """The most recent test, which is the one whose verdict stands."""
        rows = list(self.lab_tests or [])
        return max(rows, key=lambda row: row.created_at) if rows else None

    def __repr__(self) -> str:  # pragma: no cover
        return f"<HoneyBatch {self.batch_code} {self.status} {self.quantity}{self.unit.label}>"


__all__ = ["HoneyBatch", "BATCH_STATUS_ENUM", "BATCH_STAGE_ENUM"]
