"""``kvic_clusters`` — rural beekeeping cluster registry.

A cluster is the organisational unit KVIC works through: a group of beekeepers
in a district, with a coordinator. Later phases attach hives, IoT devices and
honey batches to the cluster; this table is the anchor those relationships will
point at, and it already supports membership today.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import Boolean, CheckConstraint, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:  # pragma: no cover
    from app.models.beekeeper import Beekeeper


class KvicCluster(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A beekeeping cluster overseen by KVIC."""

    __tablename__ = "kvic_clusters"

    #: Human-readable identifier, e.g. ``KVIC-GNT-001``. Unique, generated by
    #: the backend when not supplied explicitly.
    cluster_code: Mapped[str] = mapped_column(String(40), nullable=False, unique=True, index=True)
    cluster_name: Mapped[str] = mapped_column(String(160), nullable=False)

    district: Mapped[str] = mapped_column(String(80), nullable=False, index=True)
    state: Mapped[str] = mapped_column(String(80), nullable=False, index=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    coordinator_name: Mapped[str | None] = mapped_column(String(120), nullable=True)
    coordinator_phone: Mapped[str | None] = mapped_column(String(20), nullable=True)

    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )

    __table_args__ = (
        CheckConstraint("length(cluster_name) >= 3", name="cluster_name_min_length"),
        Index("ix_kvic_clusters_district_active", "district", "is_active"),
        Index("ix_kvic_clusters_state_active", "state", "is_active"),
    )

    beekeepers: Mapped[list["Beekeeper"]] = relationship(back_populates="cluster")

    @property
    def member_count(self) -> int:
        """Number of beekeepers currently assigned (requires a loaded relation)."""
        return len(self.beekeepers) if self.beekeepers is not None else 0

    def __repr__(self) -> str:  # pragma: no cover
        return f"<KvicCluster {self.cluster_code} active={self.is_active}>"
