"""Phase 2 — user profiles, beekeepers, KVIC clusters and the audit log.

Adds the tables behind the User, Role & Beekeeper Management module:

``user_profiles``
    Optional personal and address details, one row per user, created on first
    use. Every column is nullable: the platform must not require personal
    information to create an account.

``kvic_clusters``
    The organisational unit KVIC works through. Created before ``beekeepers``
    because the membership foreign key points at it.

``beekeepers``
    Apiary details for BEEKEEPER accounts. ``beekeeper_code`` is unique and
    generated by the backend from ``document_sequences``; the row always starts
    as ``PENDING`` because the platform never verifies a beekeeper on its own.

``beekeeper_verification_history``
    Append-only trail of review decisions. Nothing updates or deletes rows here;
    the current status is denormalised onto ``beekeepers`` for fast filtering.

``audit_logs``
    Append-only record of platform events, written by ``AuditService``. Actor
    columns are ``SET NULL`` so the log outlives the accounts it refers to.

``document_sequences``
    Atomic counters for human-readable codes (``BKR-GNT-00001``). Deriving codes
    from COUNT(*) would collide under concurrent registration and reuse numbers
    after a deletion, so they come from a locked per-scope counter instead.

It also extends ``users`` with ``is_verified`` (contact verification, distinct
from a beekeeper's verification status) and ``deactivated_at``.

Revision ID: c71dce65bc61
Revises: 37a03aa5a040
Create Date: 2026-09-22 18:50:10.802002+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71dce65bc61'
down_revision: Union[str, None] = '37a03aa5a040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Shared PostgreSQL enum for the beekeeper review lifecycle.
verification_status_enum = postgresql.ENUM(
    "PENDING",
    "UNDER_REVIEW",
    "VERIFIED",
    "REJECTED",
    "SUSPENDED",
    name="verification_status",
    create_type=False,
)


def upgrade() -> None:
    # The enum type is created once, explicitly. Both tables below reference it
    # with ``create_type=False`` so a second CREATE TYPE cannot be attempted.
    verification_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('document_sequences',
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('last_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences'))
    )
    op.create_index(op.f('ix_document_sequences_scope'), 'document_sequences', ['scope'], unique=True)
    op.create_table('kvic_clusters',
    sa.Column('cluster_code', sa.String(length=40), nullable=False),
    sa.Column('cluster_name', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coordinator_name', sa.String(length=120), nullable=True),
    sa.Column('coordinator_phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(cluster_name) >= 3', name=op.f('ck_kvic_clusters_cluster_name_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kvic_clusters'))
    )
    op.create_index(op.f('ix_kvic_clusters_cluster_code'), 'kvic_clusters', ['cluster_code'], unique=True)
    op.create_index(op.f('ix_kvic_clusters_district'), 'kvic_clusters', ['district'], unique=False)
    op.create_index('ix_kvic_clusters_district_active', 'kvic_clusters', ['district', 'is_active'], unique=False)
    op.create_index(op.f('ix_kvic_clusters_state'), 'kvic_clusters', ['state'], unique=False)
    op.create_index('ix_kvic_clusters_state_active', 'kvic_clusters', ['state', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('beekeepers',
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('beekeeper_code', sa.String(length=40), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('bee_species', sa.String(length=80), nullable=True),
    sa.Column('number_of_hives', sa.Integer(), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('mandal', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('kvic_cluster_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('verification_status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('verification_remarks', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$'", name=op.f('ck_beekeepers_beekeeper_pincode_format')),
    sa.CheckConstraint('experience_years IS NULL OR (experience_years >= 0 AND experience_years <= 90)', name=op.f('ck_beekeepers_experience_years_range')),
    sa.CheckConstraint('number_of_hives IS NULL OR (number_of_hives >= 0 AND number_of_hives <= 100000)', name=op.f('ck_beekeepers_number_of_hives_range')),
    sa.ForeignKeyConstraint(['kvic_cluster_id'], ['kvic_clusters.id'], name=op.f('fk_beekeepers_kvic_cluster_id_kvic_clusters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_beekeepers_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_beekeepers_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beekeepers'))
    )
    op.create_index(op.f('ix_beekeepers_beekeeper_code'), 'beekeepers', ['beekeeper_code'], unique=True)
    op.create_index('ix_beekeepers_cluster_status', 'beekeepers', ['kvic_cluster_id', 'verification_status'], unique=False)
    op.create_index(op.f('ix_beekeepers_district'), 'beekeepers', ['district'], unique=False)
    op.create_index('ix_beekeepers_district_status', 'beekeepers', ['district', 'verification_status'], unique=False)
    op.create_index(op.f('ix_beekeepers_kvic_cluster_id'), 'beekeepers', ['kvic_cluster_id'], unique=False)
    op.create_index(op.f('ix_beekeepers_state'), 'beekeepers', ['state'], unique=False)
    op.create_index(op.f('ix_beekeepers_user_id'), 'beekeepers', ['user_id'], unique=True)
    op.create_index(op.f('ix_beekeepers_verification_status'), 'beekeepers', ['verification_status'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('profile_photo', sa.String(length=512), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('mandal', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male', 'female', 'other', 'prefer_not_to_say')", name=op.f('ck_user_profiles_gender_allowed_values')),
    sa.CheckConstraint("pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$'", name=op.f('ck_user_profiles_pincode_format')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles'))
    )
    op.create_index(op.f('ix_user_profiles_district'), 'user_profiles', ['district'], unique=False)
    op.create_index(op.f('ix_user_profiles_state'), 'user_profiles', ['state'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('beekeeper_verification_history',
    sa.Column('beekeeper_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('previous_status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status', create_type=False), nullable=True),
    sa.Column('new_status', postgresql.ENUM('PENDING', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status', create_type=False), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('changed_by_name', sa.String(length=120), nullable=True),
    sa.Column('changed_by_role', sa.String(length=40), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['beekeepers.id'], name=op.f('fk_beekeeper_verification_history_beekeeper_id_beekeepers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_beekeeper_verification_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beekeeper_verification_history'))
    )
    op.create_index('ix_beekeeper_verification_beekeeper_changed', 'beekeeper_verification_history', ['beekeeper_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_beekeeper_verification_history_beekeeper_id'), 'beekeeper_verification_history', ['beekeeper_id'], unique=False)
    op.create_index(op.f('ix_beekeeper_verification_history_changed_at'), 'beekeeper_verification_history', ['changed_at'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    # Existing accounts were created before contact verification existed; they
    # keep their access and are left unverified rather than being back-filled
    # with a status nobody confirmed.


def downgrade() -> None:
    # Drops in reverse dependency order: children before the tables they point
    # at, and the enum type last.
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_beekeeper_verification_history_changed_at'), table_name='beekeeper_verification_history')
    op.drop_index(op.f('ix_beekeeper_verification_history_beekeeper_id'), table_name='beekeeper_verification_history')
    op.drop_index('ix_beekeeper_verification_beekeeper_changed', table_name='beekeeper_verification_history')
    op.drop_table('beekeeper_verification_history')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_state'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_district'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_beekeepers_verification_status'), table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_user_id'), table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_state'), table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_kvic_cluster_id'), table_name='beekeepers')
    op.drop_index('ix_beekeepers_district_status', table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_district'), table_name='beekeepers')
    op.drop_index('ix_beekeepers_cluster_status', table_name='beekeepers')
    op.drop_index(op.f('ix_beekeepers_beekeeper_code'), table_name='beekeepers')
    op.drop_table('beekeepers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_kvic_clusters_state_active', table_name='kvic_clusters')
    op.drop_index(op.f('ix_kvic_clusters_state'), table_name='kvic_clusters')
    op.drop_index('ix_kvic_clusters_district_active', table_name='kvic_clusters')
    op.drop_index(op.f('ix_kvic_clusters_district'), table_name='kvic_clusters')
    op.drop_index(op.f('ix_kvic_clusters_cluster_code'), table_name='kvic_clusters')
    op.drop_table('kvic_clusters')
    op.drop_index(op.f('ix_document_sequences_scope'), table_name='document_sequences')
    op.drop_table('document_sequences')

    # ``drop_table`` does not remove a PostgreSQL enum type. Without this, a
    # later ``upgrade`` would fail with "type verification_status already exists".
    verification_status_enum.drop(op.get_bind(), checkfirst=True)
