"""Beekeeper schemas — registration, self-service, officer management, verification."""

from __future__ import annotations

import uuid
from datetime import date, datetime

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator, model_validator

from app.models.enums import VerificationStatus
from app.schemas.profile import ProfileLocation


class BeekeeperPractice(BaseModel):
    """Apiary practice details."""

    model_config = ConfigDict(extra="forbid")

    experience_years: int | None = Field(default=None, ge=0, le=90, examples=[5])
    bee_species: str | None = Field(
        default=None, max_length=80, examples=["Apis cerana indica"]
    )
    number_of_hives: int | None = Field(default=None, ge=0, le=100000, examples=[12])

    @field_validator("bee_species")
    @classmethod
    def _clean_species(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = " ".join(value.split())
        return cleaned or None


class BeekeeperCreate(BeekeeperPractice, ProfileLocation):
    """Beekeeper details supplied during registration.

    Two fields are deliberately absent:

    * ``beekeeper_code`` — generated by the backend from a locked counter.
    * ``kvic_cluster_id`` — cluster membership is an organisational decision an
      officer makes after review, not something a public form can claim.

    ``extra="forbid"`` turns an attempt to send either into a 422 rather than a
    silently ignored field.
    """


class BeekeeperSelfUpdate(BeekeeperPractice, ProfileLocation):
    """What a beekeeper may change about their own record.

    Excludes ``kvic_cluster_id``, ``verification_status`` and
    ``beekeeper_code`` — those are officer- or system-controlled.
    """


class BeekeeperUpdate(BeekeeperSelfUpdate):
    """What an administrator or KVIC officer may change."""

    kvic_cluster_id: uuid.UUID | None = None


class BeekeeperClusterInfo(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    cluster_code: str
    cluster_name: str
    district: str
    is_active: bool


class BeekeeperOwnerInfo(BaseModel):
    """Identity of the account behind the beekeeper record."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    name: str
    email: EmailStr
    phone: str | None = None
    is_active: bool
    is_verified: bool
    last_login_at: datetime | None = None
    created_at: datetime


class BeekeeperPublic(BaseModel):
    """Full beekeeper representation for detail views."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    beekeeper_code: str
    experience_years: int | None = None
    bee_species: str | None = None
    number_of_hives: int | None = None
    village: str | None = None
    mandal: str | None = None
    district: str | None = None
    state: str | None = None
    pincode: str | None = None
    registration_date: date | None = None
    verification_status: VerificationStatus
    verification_label: str = ""
    verification_remarks: str | None = None
    verified_at: datetime | None = None
    created_at: datetime
    updated_at: datetime

    user: BeekeeperOwnerInfo
    cluster: BeekeeperClusterInfo | None = None


class BeekeeperListItem(BaseModel):
    """Row shape for directory tables — avoids shipping full detail per row."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    beekeeper_code: str
    name: str
    email: EmailStr
    phone: str | None = None
    village: str | None = None
    mandal: str | None = None
    district: str | None = None
    state: str | None = None
    experience_years: int | None = None
    bee_species: str | None = None
    number_of_hives: int | None = None
    verification_status: VerificationStatus
    verification_label: str = ""
    cluster_id: uuid.UUID | None = None
    cluster_code: str | None = None
    cluster_name: str | None = None
    registration_date: date | None = None
    created_at: datetime


class VerificationChangeRequest(BaseModel):
    """``PATCH /api/v1/beekeepers/{id}/verification`` request body."""

    model_config = ConfigDict(extra="forbid")

    status: VerificationStatus
    remarks: str | None = Field(
        default=None,
        max_length=1000,
        description="Explanation recorded in the verification history and audit log.",
        examples=["Verified by KVIC officer after field visit"],
    )

    @field_validator("remarks")
    @classmethod
    def _clean_remarks(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = " ".join(value.split())
        return cleaned or None

    @model_validator(mode="after")
    def _negative_decisions_need_a_reason(self) -> "VerificationChangeRequest":
        """Rejections and suspensions must be explained.

        A model-level check rather than a field one: a field validator does not
        run when the field is simply absent, which is exactly the case that
        matters here.
        """
        if self.status in (VerificationStatus.REJECTED, VerificationStatus.SUSPENDED):
            if not self.remarks or len(self.remarks) < 5:
                raise ValueError(
                    "Please provide a remark explaining this decision "
                    "(at least 5 characters)"
                )
        return self


class VerificationHistoryEntry(BaseModel):
    """One row of the append-only verification trail."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    previous_status: VerificationStatus | None = None
    new_status: VerificationStatus
    remarks: str | None = None
    changed_by_id: uuid.UUID | None = None
    changed_by_name: str | None = None
    changed_by_role: str | None = None
    changed_at: datetime


class BeekeeperDetail(BaseModel):
    """Beekeeper detail view: record plus its verification trail."""

    beekeeper: BeekeeperPublic
    verification_history: list[VerificationHistoryEntry] = Field(default_factory=list)
    allowed_next_statuses: list[VerificationStatus] = Field(default_factory=list)


class BeekeeperFilterOptions(BaseModel):
    """Values available for the directory filters, derived from stored data."""

    districts: list[str]
    states: list[str]
    bee_species: list[str]
    verification_statuses: list[str]


class BeekeeperSummary(BaseModel):
    """Aggregate counts for the management screens. All values come from the database."""

    total: int
    by_verification_status: dict[str, int]
    by_district: list[dict[str, object]]
    assigned_to_cluster: int


class BeekeeperRegistrationInfo(BaseModel):
    """Result returned alongside the auth payload when a beekeeper registers."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    beekeeper_code: str
    verification_status: VerificationStatus
    district: str | None = None
    state: str | None = None


# --------------------------------------------------------------------------- #
# Projections
#
# These live in the schema layer because they are pure presentation: they turn a
# loaded ORM object into the shape a specific endpoint promises. Keeping them
# here means routes stay free of mapping code and every endpoint that returns a
# beekeeper describes it identically.
# --------------------------------------------------------------------------- #
def _cluster_block(beekeeper) -> dict | None:
    cluster = getattr(beekeeper, "cluster", None)
    if cluster is None:
        return None
    return {
        "id": cluster.id,
        "cluster_code": cluster.cluster_code,
        "cluster_name": cluster.cluster_name,
        "district": cluster.district,
        "is_active": cluster.is_active,
    }


def _owner_block(beekeeper) -> dict:
    user = beekeeper.user
    return {
        "id": user.id,
        "name": user.name,
        "email": user.email,
        "phone": user.phone,
        "is_active": user.is_active,
        "is_verified": user.is_verified,
        "last_login_at": user.last_login_at,
        "created_at": user.created_at,
    }


def to_beekeeper_public(beekeeper) -> BeekeeperPublic:
    """Full representation for a detail view."""
    cluster = getattr(beekeeper, "cluster", None)
    return BeekeeperPublic(
        id=beekeeper.id,
        beekeeper_code=beekeeper.beekeeper_code,
        experience_years=beekeeper.experience_years,
        bee_species=beekeeper.bee_species,
        number_of_hives=beekeeper.number_of_hives,
        village=beekeeper.village,
        mandal=beekeeper.mandal,
        district=beekeeper.district,
        state=beekeeper.state,
        pincode=beekeeper.pincode,
        registration_date=beekeeper.registration_date,
        verification_status=VerificationStatus(beekeeper.verification_status),
        verification_label=VerificationStatus(beekeeper.verification_status).label,
        verification_remarks=beekeeper.verification_remarks,
        verified_at=beekeeper.verified_at,
        created_at=beekeeper.created_at,
        updated_at=beekeeper.updated_at,
        user=BeekeeperOwnerInfo(**_owner_block(beekeeper)),
        cluster=BeekeeperClusterInfo(**_cluster_block(beekeeper)) if cluster else None,
    )


def to_beekeeper_list_item(beekeeper) -> BeekeeperListItem:
    """Compact row for directory tables.

    Carries the owner's name and email because an officer scanning the queue
    needs to identify people, not just UUIDs, but omits the audit fields that
    only the detail view shows.
    """
    user = beekeeper.user
    cluster = getattr(beekeeper, "cluster", None)
    return BeekeeperListItem(
        id=beekeeper.id,
        beekeeper_code=beekeeper.beekeeper_code,
        name=user.name,
        email=user.email,
        phone=user.phone,
        village=beekeeper.village,
        mandal=beekeeper.mandal,
        district=beekeeper.district,
        state=beekeeper.state,
        experience_years=beekeeper.experience_years,
        bee_species=beekeeper.bee_species,
        number_of_hives=beekeeper.number_of_hives,
        verification_status=VerificationStatus(beekeeper.verification_status),
        verification_label=VerificationStatus(beekeeper.verification_status).label,
        cluster_id=beekeeper.kvic_cluster_id,
        cluster_code=cluster.cluster_code if cluster else None,
        cluster_name=cluster.cluster_name if cluster else None,
        registration_date=beekeeper.registration_date,
        created_at=beekeeper.created_at,
    )


def to_beekeeper_detail(beekeeper) -> BeekeeperDetail:
    """Detail view plus the append-only verification trail."""
    current = VerificationStatus(beekeeper.verification_status)
    return BeekeeperDetail(
        beekeeper=to_beekeeper_public(beekeeper),
        verification_history=[
            VerificationHistoryEntry.model_validate(entry)
            for entry in beekeeper.verification_history
        ],
        allowed_next_statuses=VerificationStatus.allowed_transitions(current),
    )


__all__ = [
    "BeekeeperCreate",
    "BeekeeperSelfUpdate",
    "BeekeeperUpdate",
    "BeekeeperPublic",
    "BeekeeperListItem",
    "BeekeeperDetail",
    "BeekeeperFilterOptions",
    "BeekeeperSummary",
    "BeekeeperRegistrationInfo",
    "VerificationChangeRequest",
    "VerificationHistoryEntry",
    "to_beekeeper_public",
    "to_beekeeper_list_item",
    "to_beekeeper_detail",
]
