"""KVIC cluster schemas."""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ClusterBase(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cluster_name: str = Field(min_length=3, max_length=160, examples=["Tenali Beekeeping Cluster"])
    district: str = Field(min_length=2, max_length=80, examples=["Guntur"])
    state: str = Field(min_length=2, max_length=80, examples=["Andhra Pradesh"])
    description: str | None = Field(default=None, max_length=1000)
    coordinator_name: str | None = Field(default=None, max_length=120)
    coordinator_phone: str | None = Field(default=None, max_length=20)

    @field_validator("cluster_name", "district", "state")
    @classmethod
    def _clean_required(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if len(cleaned) < 2:
            raise ValueError("This field must contain at least 2 characters")
        return cleaned

    @field_validator("coordinator_phone")
    @classmethod
    def _clean_phone(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip().replace(" ", "").replace("-", "")
        if not cleaned:
            return None
        if not cleaned.startswith("+") and cleaned.isdigit() and len(cleaned) == 10:
            cleaned = f"+91{cleaned}"
        if not (cleaned.startswith("+") and cleaned[1:].isdigit() and 8 <= len(cleaned) <= 16):
            raise ValueError("Enter a valid phone number, e.g. 9876543210 or +919876543210")
        return cleaned


class ClusterCreate(ClusterBase):
    """``POST /api/v1/clusters``.

    ``cluster_code`` is optional: omit it and the backend generates one
    (``KVIC-GNT-001``); supply it only when migrating an existing registry.
    """

    cluster_code: str | None = Field(
        default=None,
        max_length=40,
        description="Optional. Generated by the backend when omitted.",
        examples=["KVIC-GNT-001"],
    )

    @field_validator("cluster_code")
    @classmethod
    def _clean_code(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip().upper().replace(" ", "-")
        return cleaned or None


class ClusterUpdate(BaseModel):
    """``PUT /api/v1/clusters/{id}`` — partial update of editable fields."""

    model_config = ConfigDict(extra="forbid")

    cluster_name: str | None = Field(default=None, min_length=3, max_length=160)
    district: str | None = Field(default=None, min_length=2, max_length=80)
    state: str | None = Field(default=None, min_length=2, max_length=80)
    description: str | None = Field(default=None, max_length=1000)
    coordinator_name: str | None = Field(default=None, max_length=120)
    coordinator_phone: str | None = Field(default=None, max_length=20)

    @field_validator("coordinator_phone")
    @classmethod
    def _clean_phone(cls, value: str | None) -> str | None:
        return ClusterBase._clean_phone(value)


class ClusterStatusUpdate(BaseModel):
    """``PATCH /api/v1/clusters/{id}/status``."""

    model_config = ConfigDict(extra="forbid")

    is_active: bool
    reason: str | None = Field(default=None, max_length=200)


class ClusterPublic(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    cluster_code: str
    cluster_name: str
    district: str
    state: str
    description: str | None = None
    coordinator_name: str | None = None
    coordinator_phone: str | None = None
    is_active: bool
    created_at: datetime
    updated_at: datetime


class ClusterWithCounts(ClusterPublic):
    """Cluster plus its member count (a database aggregate, not an estimate)."""

    member_count: int = 0


class ClusterDetail(BaseModel):
    cluster: ClusterPublic
    member_count: int = 0
    members: list[dict] = Field(default_factory=list)


# --------------------------------------------------------------------------- #
# Projections
# --------------------------------------------------------------------------- #
def to_cluster_public(cluster, member_count: int = 0) -> ClusterWithCounts:
    """Cluster plus its member count.

    ``member_count`` is passed in from a single aggregate query rather than read
    from ``cluster.beekeepers``, which would trigger one SELECT per row when
    listing clusters.
    """
    return ClusterWithCounts(
        id=cluster.id,
        cluster_code=cluster.cluster_code,
        cluster_name=cluster.cluster_name,
        district=cluster.district,
        state=cluster.state,
        description=cluster.description,
        coordinator_name=cluster.coordinator_name,
        coordinator_phone=cluster.coordinator_phone,
        is_active=cluster.is_active,
        created_at=cluster.created_at,
        updated_at=cluster.updated_at,
        member_count=member_count,
    )


__all__ = [
    "ClusterCreate",
    "ClusterUpdate",
    "ClusterStatusUpdate",
    "ClusterPublic",
    "ClusterWithCounts",
    "ClusterDetail",
    "to_cluster_public",
]
